version: "3.3"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

  api:
    image: httpsantos/api-boticario
    restart: on-failure
    depends_on:
      - "db"
    ports:
      - "3333:3333"